// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCEcrc9X8LGLWkoRmZXzF8UxMyvzQtw98',
    appId: '1:37864253015:web:533812cd32cd3badd1a512',
    messagingSenderId: '37864253015',
    projectId: 'cchat-app-2c52d',
    authDomain: 'cchat-app-2c52d.firebaseapp.com',
    storageBucket: 'cchat-app-2c52d.appspot.com',
    measurementId: 'G-8F06VFL8P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHTeiB5PFXyCRNVvDKLNLFv-ZG27ps3Mw',
    appId: '1:37864253015:android:da10b5244f15926fd1a512',
    messagingSenderId: '37864253015',
    projectId: 'cchat-app-2c52d',
    storageBucket: 'cchat-app-2c52d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWOfezTMwNhu_GqHVr9CCHRzLD_DgoN-Q',
    appId: '1:37864253015:ios:3128dc48c6424e4cd1a512',
    messagingSenderId: '37864253015',
    projectId: 'cchat-app-2c52d',
    storageBucket: 'cchat-app-2c52d.appspot.com',
    iosClientId: '37864253015-p1pouijbqu7jaqc6vftqht4kg61ckor3.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
